<?php 
### CONFIGURATION FILE AUTOMATICALLY GENERATED BY THE OXYGEN WEBHELP INSTALLER AT 2014-08-02 00:52:52 ###
### for api_ref_guide 3.6.0 

// The URL where the webhelp is installed on with trailing /
define('__BASE_URL__',"http://localhost/api_ref_guide/");

// The relative URL where the webhelp is installed on with trailing /
define('__BASE_PATH__',"/api_ref_guide/");

// Email address to be used as from in sent emails
define('__EMAIL__',"mary@platfora.com");

// Email address to be notified when error occur
define('__ADMIN_EMAIL__',"mary@platfora.com");

// Send errors to system administartor?
define('__SEND_ERRORS__',true);

// If the system is moderated each post must be confirmed by moderator
define('__MODERATE__', true);

// User session life time in seconds, by default is 7 days
define('__SESSION_LIFETIME__',604800);

// Is unauthenticated user allowed to post comments
define('__GUEST_POST__', true);

// User friendly Product name
define('__PRODUCT_NAME__','oxy-webhelp');

// Show comments form other products with the same version from the same database
//define('__SHARE_WITH__',"'editor','diff'");

// Data base connection info
$dbConnectionInfo['dbName']="platcomments";
$dbConnectionInfo['dbUser']="mary";
$dbConnectionInfo['dbPassword']="foobar";
$dbConnectionInfo['dbHost']="localhost";

?>